# Generated by Django 4.1.5 on 2023-01-18 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_remove_category_sous_category_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlenote",
            name="id_sous_category",
        ),
        migrations.AddField(
            model_name="articlenote",
            name="sous_cat_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.sous_category",
            ),
        ),
    ]
