# Generated by Django 3.2.4 on 2021-07-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumiere', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_path',
            field=models.CharField(default='/static/image/default/photo_a_venir.png', max_length=100),
        ),
    ]
